# need to set 'ruleSelectorNilUsesHelmValues' in helm chart to false so helm annotations and labels not necessary
# examples: https://alex.dzyoba.com/blog/prometheus-alerts/
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: spring-micro-with-actuator.rules
  namespace: default
spec:
  groups:
  - name: spring-micro-with-actuator.rules
    rules:
    - alert: Low inventory on product
      annotations:
        description: product has reached low inventory levels
        summary: low inventory, need to reorder product from supplier
      expr: low_inventory_count{job="spring-micro-with-actuator"}<3
      for: 1m
      labels:
        severity: critical
