# need to set 'ruleSelectorNilUsesHelmValues' in helm chart to false so helm annotations and labels not necessary
# examples: https://alex.dzyoba.com/blog/prometheus-alerts/
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: spring-micro-with-actuator.rules
  namespace: default
spec:
  groups:
  - name: spring-micro-with-actuator.rules
    rules:
    - alert: LowProductInventory
      annotations:
        description: on {{ $externalLabels.cluster }}, product {{ $labels.pname }} has reached low inventory levels, only {{ $value }} left
        remediation: login to {{ $externalLabels.env }} cluster {{ $externalLabels.cluster }} using jumpbox {{ $externalLabels.jumpbox }} and order more {{ $labels.pname }} using the /swagger-ui/index.html page
      expr: low_inventory_count{job="spring-micro-with-actuator"}<3
      for: 10s # 1m
      labels:
        severity: critical
