apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    # specified as matchLabel in 'Prometheus' CRD
    # this ServiceMonitor will not be found by prometheus unless it matches
    release: prom-stack
  name: spring-rest-micro-with-actuator
  # does not need to be in 'prom' namespace, works fine in default
  namespace: default
spec:
  endpoints:

  # basic set of metrics exposed at main /metrics
  - path: /metrics
    port: http
    scheme: http
    interval: 60s

  # main Java Actuator metrics enabled by adding 'spring-boot-starter-actuator' dependency to Spring Boot
  - path: /actuator/prometheus
    port: http-actuator-metrics
    scheme: http
    interval: 60s

  # custom Actuator metrics enabled by adding 'micrometer-registry-prometheus' dependency to Spring Boot
  # then creating CustomPrometheusEndpoint Bean as ControllerEndpoint
  - path: /actuator/prometheus-custom
    port: http-actuator-metrics
    scheme: http
    interval: 15s

  jobLabel: spring-rest
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: spring-micro-with-actuator
